# Copyright 2020 JanusGraph Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI Backend Cassandra

on:
  pull_request:
  push:

env:
  BUILD_MAVEN_OPTS: "-DskipTests=true --batch-mode --also-make"
  VERIFY_MAVEN_OPTS: "-Pcoverage"

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - args: "-Pcassandra3-byteordered -Dtest=\"**/diskstorage/cassandra/*\""
            name: byteordered-diskstorage
          - args: "-Pcassandra3-murmur -Dtest=\"**/diskstorage/cassandra/*\""
            name: murmur-diskstorage
          - args: "-Pcassandra3-byteordered -Dtest=\"**/graphdb/cassandra/*\""
            name: byteordered-graphdb
          - args: "-Pcassandra3-murmur -Dtest=\"**/graphdb/cassandra/*\""
            name: murmur-graphdb
          - args: "-Pcassandra3-murmur -Dtest=\"**/hadoop/*\""
            name: murmur-hadoop
          - args: "-Pcassandra3-byteordered -Dtest=\"**/core/cassandra/*\""
            name: byteordered-core
          - args: "-Pcassandra3-murmur -Dtest=\"**/core/cassandra/*\""
            name: murmur-core
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: mvn clean install ${{ env.BUILD_MAVEN_OPTS }} ${{ matrix.install-args }}
      - run: mvn verify ${{ env.VERIFY_MAVEN_OPTS }} ${{ matrix.args }}
      - uses: actions/upload-artifact@v2
        with:
          name: jacoco-reports
          path: target/jacoco-combined.exec
      - uses: codecov/codecov-action@v1
        with:
          name: codecov-cassandra-${{ matrix.name }}

  full-tests:
    runs-on: ubuntu-20.04
    if: "github.event_name == 'push' && contains(github.event.head_commit.message, '[full-tests]') || github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[full-tests]')"
    strategy:
      fail-fast: false
      matrix:
        include:
          - args: "-Pcassandra3-byteordered -Dtest=\"**/diskstorage/cassandra/*\""
          - args: "-Pcassandra3-murmur -Dtest=\"**/diskstorage/cassandra/*\""
          - args: "-Pcassandra3-byteordered -Dtest=\"**/graphdb/cassandra/*\""
          - args: "-Pcassandra3-murmur -Dtest=\"**/graphdb/cassandra/*\""
          - args: "-Pcassandra3-murmur -Dtest=\"**/hadoop/*\""
          - args: "-Pcassandra3-byteordered -Dtest=\"**/core/cassandra/*\""
          - args: "-Pcassandra3-murmur -Dtest=\"**/core/cassandra/*\""
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: mvn clean install ${{ env.BUILD_MAVEN_OPTS }} ${{ matrix.install-args }}
      - run: mvn verify -Dcassandra.docker.version='3.0.18' ${{ env.VERIFY_MAVEN_OPTS }} ${{ matrix.args }}
